# Supabase Configuration File
# https://supabase.com/docs/guides/functions

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[functions.telegram-bot]
verify_jwt = false

[functions.set-webhook]
verify_jwt = false

